server:
  port: 8080

spring:
  application:
    name: apigateway
  main:
    allow-bean-definition-overriding: true
    allow-circular-references: true
  profiles:
    active: development
  cloud:
    config:
      enabled: false

eureka:
  instance:
    hostname: localhost
  client:
    enabled: true
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 20000
# Map path to auth service
zuul:
  host:
    connect-timeout-millis: 10000
    socket-timeout-millis: 60000
  routes:
    identity-service:
      path: /identity/**
      url: http://localhost:9191
      service-id: IDENTITYSERVICE
      sensitive-headers: Cookie,Set-Cookie

    order-service:
      path: /order/**
      url: http://localhost:9192
      service-id: ORDERSERVICE
      sensitive-headers: Cookie,Set-Cookie

    inventory-service:
      path: /inventory/**
      url: http://localhost:9193
      service-id: INVENTORYANDCATALOGSERVICE
      sensitive-headers: Cookie,Set-Cookie




security:
  jwt:
    uri: /identity/users/login/**