server:
  port: 8080

eureka:
  instance:
    hostname: localhost

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: Identity-Service
          uri: http://localhost:9191/
          predicates:
            - Path=/identity/**
          filters:
            - RewritePath=/identity/(?<segment>.*), /$\{segment}
        - id: Order-Service
          uri: http://localhost:9192/
          predicates:
            - Path=/order/**
          filters:
            - RewritePath=/order/(?<segment>.*), /$\{segment}
        - id: InventoryManagementCatalog-Service
          uri: http://localhost:9193/
          predicates:
            - Path=/inventory/**
          filters:
            - RewritePath=/inventory/(?<segment>.*), /$\{segment}